kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  # Control-plane node
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP

  # Worker node 1
  - role: worker

  # Worker node 2
  - role: worker
