apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-schema
data:
  lms.sql: |
    -- phpMyAdmin SQL Dump
    -- version 5.2.0
    -- https://www.phpmyadmin.net/
    --
    -- Host: 127.0.0.1
    -- Generation Time: Sep 27, 2023 at 10:27 PM
    -- Server version: 10.4.27-MariaDB
    -- PHP Version: 8.2.0

    SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
    START TRANSACTION;
    SET time_zone = "+00:00";


    /*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
    /*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
    /*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
    /*!40101 SET NAMES utf8mb4 */;

    --
    -- Database: `lms`
    --
    CREATE DATABASE IF NOT EXISTS lms;
    USE lms;

    -- --------------------------------------------------------

    --
    -- Table structure for table `teams`
    --

    CREATE TABLE `teams` (
      `ID` int(11) NOT NULL,
      `NameOfTeam` varchar(255) NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

    --
    -- Dumping data for table `teams`
    --

    INSERT INTO `teams` (`ID`, `NameOfTeam`) VALUES
    (1, 'testing'),
    (5, 'algo'),
    (101, 'admin'),
    (133, 'NULL');

    -- --------------------------------------------------------

    --
    -- Table structure for table `training`
    --

    CREATE TABLE `training` (
      `Training_name` varchar(255) NOT NULL,
      `Training_state` int(11) NOT NULL,
      `Emp_id` int(11) NOT NULL,
      `id` int(11) NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

    --
    -- Dumping data for table `training`
    --

    INSERT INTO `training` (`Training_name`, `Training_state`, `Emp_id`, `id`) VALUES
    ('math', 5, 2, 1),
    ('testing', 5, 2, 568),
    ('algo', 5, 2, 570),
    ('cryptography', 1, 2, 571),
    ('cyper', 20, 2, 572),
    ('testing', 0, 2, 575);

    -- --------------------------------------------------------

    --
    -- Table structure for table `user`
    --

    CREATE TABLE `user` (
      `user_id` int(11) NOT NULL,
      `Name` varchar(25) NOT NULL,
      `Email` varchar(50) NOT NULL,
      `Password` varchar(50) NOT NULL,
      `Phone` int(11) NOT NULL,
      `Status` int(11) NOT NULL,
      `Type` int(11) NOT NULL,
      `Team_id` int(11) NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

    --
    -- Dumping data for table `user`
    --

    INSERT INTO `user` (`user_id`, `Name`, `Email`, `Password`, `Phone`, `Status`, `Type`, `Team_id`) VALUES
    (2, 'assem', 'assem@gmail.com', '11Aa', 11111111, 1, 3, 1),
    (3, 'ahmed', 'ahmedkhaled@gmail.com', '11Aa', 11111111, 1, 2, 1),
    (10, 'rama', 'rama@gmail.com', '11Aa', 11111111, 1, 1, 101),
    (111, 'yousra', 'yousra@gmail.com', '11Aa', 123456, 1, 3, 1),
    (113, 'yousra', 'aaa@gmail.com', '11Aa', 123456, 1, 2, 5);

    --
    -- Indexes for dumped tables
    --

    --
    -- Indexes for table `teams`
    --
    ALTER TABLE `teams`
      ADD PRIMARY KEY (`ID`);

    --
    -- Indexes for table `training`
    --
    ALTER TABLE `training`
      ADD PRIMARY KEY (`id`),
      ADD KEY `CONS_1` (`Emp_id`);

    --
    -- Indexes for table `user`
    --
    ALTER TABLE `user`
      ADD PRIMARY KEY (`user_id`),
      ADD KEY `vnjhn` (`Team_id`);

    --
    -- AUTO_INCREMENT for dumped tables
    --

    --
    -- AUTO_INCREMENT for table `teams`
    --
    ALTER TABLE `teams`
      MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=134;

    --
    -- AUTO_INCREMENT for table `training`
    --
    ALTER TABLE `training`
      MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=576;

    --
    -- AUTO_INCREMENT for table `user`
    --
    ALTER TABLE `user`
      MODIFY `user_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=114;

    --
    -- Constraints for dumped tables
    --

    --
    -- Constraints for table `training`
    --
    ALTER TABLE `training`
      ADD CONSTRAINT `CONS_1` FOREIGN KEY (`Emp_id`) REFERENCES `user` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE;

    --
    -- Constraints for table `user`
    --
    ALTER TABLE `user`
      ADD CONSTRAINT `vnjhn` FOREIGN KEY (`Team_id`) REFERENCES `teams` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
    COMMIT;

    /*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
    /*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
    /*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
