apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          value: lms
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-pvc
          mountPath: /var/lib/mysql
        - name: schema-init
          # mountPath: /docker-entrypoint-initdb.d/ # either use this method or the next two lines
          mountPath: /docker-entrypoint-initdb.d/lms.sql
          subPath: lms.sql
          readOnly: true
      volumes:
        - name: schema-init
          configMap:
            name: mysql-schema
        - name: mysql-pvc
          persistentVolumeClaim:
            claimName: mysql-pvc
